# h2 http://localhost:8080/h2-console
spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  servlet:
   multipart:
     max-file-size: 20MB
     max-request-size: 20MB  
  jpa:
   database: POSTGRESQL 
  datasource:
     driverClassName: org.postgresql.Driver
     url: jdbc:postgresql://localhost:5432/pictgram
     username: pictgram
     password: password   
mail:
    default-encoding: UTF-8
    protocol: smtp
    host: ${spring.mail.host}
    port: ${spring.mail.port}
    username: ${spring.mail.username}
    password: ${spring.mail.password}
    properties: 
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
thymeleaf:
    check-template-location: false
image:
  local: true
  push7:
  id: ${push7.id}  
 
  googlemap:
  key: ${googlemap.key}